#' Generate Fitness Landscape using NK Model
#'
#' A fitness landscape generated by the NK model.
#' The landscape is returned as a two-column data frame,
#' where the first column contains the coordinates of
#' the spot (class `character`) and the second column contains
#' the fitness value (class `numeric`). For more information
#' on NK models, see Kauffman & Weinberger (1989)
#' <doi:10.1016/s0022-5193(89)80019>.
#'
#' @param n corresponds to the N parameter in the NK model
#' @param k corresponds to the K parameter in the NK model
#' @return data frame containing landscape generated via NK model
#' @export
generate_nk <- function(n, k) {

}

#' Generate Fitness Landscape using RMF model
#'
#' A fitness landscape generated by the rough Mt. Fuji (RMF) model.
#' The landscape is returned as a two-column data frame,
#' where the first column contains the coordinates of
#' the spot (class `character`) and the second column contains
#' the fitness value (class `numeric`). For more information
#' on RMF models, see Aita et al. (2000)
#' <doi:10.1002/(SICI)1097-0282(200007)54:1<64::AID-BIP70>3.0.CO;2-R>.
#'
#' @param max.seq genotype for the peak of the RMF model
#' @param c corresponds to the `c` parameter in the RMJ model
#' @param eta function that returns outputs of a random variable;
#'   default value is `function() rnorm(1)`.
#' @return data frame containing landscape generated via NK model
#' @export
generate_rmf <- function(max.seq,
                         c,
                         eta = function() rnorm(1)) {

}
